---
title: "Performance"
author: "Eva Viviani"
date: '2022-06-24'
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This notebook compares the performance of the R's utility functions with their counterpart in Rcpp

```{r, message=FALSE}
rm(list = ls())
library("microbenchmark")
library("Rcpp")

c_functions_folder <- file.path(paste0(getwd(),'/src/'))
r_functions_folder <- file.path(paste0(getwd(),'/R/'))
```

Source all the R and Rcpp functions

```{r}
c_functions <- list.files(c_functions_folder, pattern = ".cpp")
r_functions <- list.files(r_functions_folder, pattern = ".R")

for (i in c_functions){
  sourceCpp(paste0(c_functions_folder,i))
}

for (i in r_functions){
  source(paste0(r_functions_folder,i))
}

```


## psUtility

```{r}
times <- c(100,200,500,1000)


```


```{r}
p <- c(aPS = 1, sPref = 3, 
       sSlow = 2, bPS = 1)
v = 1
d = 11.46856 
proc1List <- lapply(times,function(x){
  b <- microbenchmark(psUtilityR = m4ma::psUtility(p, v, d),
                      psUtilityCpp = m4ma::psUtility_rcpp(aPS = p["aPS"], sPref = p["sPref"], 
                                                    sSlow = 2, bPS = 1, 
                                                    v, d),
                      times = x)
  b$n <- x
  b
})
proc1summary <- do.call(rbind,(proc1List))
proc1summary
```

## gaUtility

```{r}
GA = c(0.33040516, 0.08040516, 0.11403929, 0.25292818, 0.36403929, 0.47515040, 0.58626151, 0.69737262, 0.83626151, 1.03070596, 1.28070596)
p <- c(
  bGA = 10,
  aGA = 2
)


proc2List <- lapply(times,function(x){
  b <- microbenchmark(gaUtilityR = m4ma::gaUtility(p, GA) ,
                      gaUtilityCpp = m4ma::gaUtility_rcpp(bGA = 10, aGA = 2, GA),
                      times = x)
  b$n <- x
  b
})
proc2summary <- do.call(rbind,(proc2List))
proc2summary

```

## caUtility
```{r}
p <- c(
  aCA = 1.5,
  bCA = 1,
  bCAlr = 10
)

proc3List <- lapply(times,function(x){
  b <- microbenchmark(caUtilityR = m4ma::caUtility(p),
                      caUtilityCpp = m4ma::caUtility_rcpp(aCA = 1.5, bCA = 1, bCAlr = 10),
                      times = x)
  b$n <- x
  b
})
proc3summary <- do.call(rbind,(proc3List))
proc3summary


```

# idUtility

```{r, eval=FALSE}
p <- c(
  'bID' = 1.3,
  'dID' = 2,
  'aID' = 2
)
n = 1
ok = matrix(data = TRUE, nrow = 11, ncol = 3)
group = c('A_1' = 1, 'a_1' = 2,
          'b_1' = 3, 'B_1' = 4,
          'C_1' = 5, 'c_1' = 6)
proc4List <- lapply(times,function(x){
  b <- microbenchmark(idUtilityR = idUtility(p, n, ID = NULL, ok, group),
                      idUtilityCpp = idUtility_rcpp(bID = 1.3, aID = 2, dID = 2, n = 1, ID = NULL, ok = ok, group = group),
                      times = x)
  b$n <- x
  b
})
proc4summary <- do.call(rbind,(proc4List))
proc4summary

```

## baUtility
```{r}
set.seed(23123)
BA = runif(6)
names(BA) = c(1:6)

p <- c(
  aBA = 1.5,
  bBA = 1
)

proc5List <- lapply(times,function(x){
  b <- microbenchmark(baUtilityR = m4ma::baUtility(p, BA),
                      baUtilityCpp = m4ma::baUtility_rcpp(1.5, 1, BA, 1:6),
                      times = x)
  b$n <- x
  b
})
proc5summary <- do.call(rbind,(proc5List))
proc5summary


```

## flUtility
```{r}
leaders = matrix(c(9, 0.5, 0.5, 8, 0.5, 0.5), ncol = 2)
row.names(leaders) <- c('cell', 'angleDisagree', 'inGroup')
set.seed(12123)
dists = t(matrix(rep(runif(33), 2), ncol = 2))

FL = list(leaders = leaders, dists = dists)

p <- c(
  aFL = 1.5,
  bFL = 1,
  dFL = 4
)

proc6List <- lapply(times,function(x){
  b <- microbenchmark(flUtilityR = m4ma::flUtility(p, FL),
                      flUtilityCpp = m4ma::flUtility_rcpp(1.5, 1, 4, leaders, dists),
                      times = x)
  b$n <- x
  b
})
proc6summary <- do.call(rbind,(proc6List))
proc6summary


```

# pCNL

```{r}
n_cells = 34
V = runif(n_cells, -10e04, 0)
V[1] = V[1]*2
muM = rep(1, 5)

nests <- list(
  Central = c(0,  6, 17, 28),
  NonCentral = c(0, 1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 17, 18 ,19 ,20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 33),
  acc = c(1,  2,  3  ,4,  5,  6,  7  ,8,  9, 10, 11),
  const = c(12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22),
  dec = c(0, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33))

alpha <- list(
  Central = c(0.3333333,  0.3333333, 0.3333333, 0.3333333),
  NonCentral = c(0.3333333, 0.5000000, 0.5000000, 0.5000000, 0.5000000, 0.3333333, 0.5000000, 0.5000000, 0.5000000, 0.5000000, 0.5000000, 0.5000000, 0.5000000,
                 0.5000000, 0.5000000, 0.3333333, 0.5000000, 0.5000000, 0.5000000, 0.5000000, 0.5000000, 0.5000000, 0.5000000, 0.5000000, 0.5000000, 0.3333333,
                 0.5000000, 0.5000000, 0.5000000, 0.5000000, 0.5000000),
  acc = c(0.5000000, 0.5000000, 0.5000000, 0.5000000, 1.0000000, 0.3333333, 0.5000000, 0.5000000, 0.5000000, 0.5000000, 0.5000000),
  const = c(0.5000000, 0.5000000, 0.5000000, 0.5000000, 1.0000000, 0.3333333, 0.5000000, 0.5000000, 0.5000000, 0.5000000, 0.5000000),
  dec = c(0.3333333, 0.5000000, 0.5000000, 0.5000000, 0.5000000, 1.0000000, 0.3333333, 0.5000000, 0.5000000, 0.5000000, 0.5000000, 0.5000000))

nests_new = list(
  Central = c(0, 6, 17, 28),
  NonCentral = c(0:33)[-c(6, 17, 28)],
  acc = c(1:11),
  const = c(12:22),
  dec = c(0, 23:33)
)

cell_nest = cbind(
  t(matrix(c(c(1, 5),           # cell 0: Central, dec
             rep(2:3, 5),       # cell 1-5: NonCentral, acc
             c(1, 3),           # cell 6: Central, acc
             rep(2:3, 5),       # cell 7-11: NonCentral, acc
             rep(c(2, 4), 5),   # cell 12-16: NonCentral, const
             c(1, 4),           # cell 17: Central, const
             rep(c(2, 4), 5),   # cell 18-22: NonCentral, const
             rep(c(2, 5), 5),   # cell 23-27: NonCentral, dec
             c(1, 5),           # cell 28: Central, dec
             rep(c(2, 5), 5)),  # cell 29-33: NonCentral, dec
           nrow = 2)),
  # Index cell in NonCentral/Central and acc/const/dec nest
  cbind(c(1, 1:5, 2, 6:15, 3, 16:25, 4, 26:30), 
        c(1, 1:11, 1:11, 2:12)))

mu = 1

maxV = max(V)

norm_sample = rnorm(34)

proc7List <- lapply(times,function(x){
  b <- microbenchmark(
 pCNLR = m4ma::pCNL(17, V, muM = muM, nests, alpha, mu, cell_nest),
 pCNLCpp = m4ma::pcnl_rcpp(cell_nest[18, ], V, muM, nests, alpha, mu),
                      times = x)
  b$n <- x
  b
})
proc7summary <- do.call(rbind,(proc7List))
proc7summary


```

# plot benchmark results

```{r, message=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(tidyr)
library(tibble)
#library(PupillometryR)
```

```{r}

# bind all outputs together 
do.call(rbind,list(proc1summary,proc2summary,proc3summary,proc5summary, proc6summary, proc7summary)) -> proc_time 
proc_time$type <- ifelse(substr(proc_time$expr,nchar(as.character(proc_time$expr)),nchar(as.character(proc_time$expr[1]))) == 'R','R','Cpp')
proc_time$type <- as.factor(proc_time$type)
proc_time$ntime <- log(proc_time$time * 0.000001, base = 10) #ms

```


## compare R and C++ single functions side by side

```{r}
y_min <- 0
p1<-ggplot(as.data.frame(proc_time), aes(x = expr, y = ntime, fill=type))+
  geom_violin(trim = T)+
  xlab("")+
  ylab("time log10(ms)")+
  coord_flip() +
  theme_bw()+
  theme(legend.position = 'top',
        legend.title =element_blank() )+
  scale_fill_manual(values=c("#E69F00","#999999"))
 p1
```

```{r, eval=FALSE}
ggsave(plot = p1, "performance_29_june.png", dpi = 300)
```

```{r}
as_tibble(proc1summary) -> proc1summary_tbl
as_tibble(proc2summary) -> proc2summary_tbl
as_tibble(proc3summary) -> proc3summary_tbl
#as_tibble(proc4summary) -> proc4summary_tbl
as_tibble(proc5summary) -> proc5summary_tbl
as_tibble(proc6summary) -> proc6summary_tbl
as_tibble(proc7summary) -> proc7summary_tbl


proc1summary_tbl%>%
  group_by(expr)%>%
  summarise(med_gain = median(time))%>%
  summarise(psUtilityR = ((lag(med_gain) - med_gain ) * 100)/lag(med_gain))%>%
  na.omit()-> proc1summary_median

proc2summary_tbl%>%
  group_by(expr)%>%
  summarise(med_gain = median(time))%>%
  summarise(gaUtilityR = ((lag(med_gain) - med_gain ) * 100)/lag(med_gain))%>%
  na.omit()-> proc2summary_median

proc3summary_tbl%>%
  group_by(expr)%>%
  summarise(med_gain = median(time))%>%
  summarise(caUtilityR = ((lag(med_gain) - med_gain ) * 100)/lag(med_gain))%>%
  na.omit()-> proc3summary_median

# proc4summary_tbl%>%
#   group_by(expr)%>%
#   summarise(med_gain = median(time))%>%
#   summarise(idUtilityR = ((lag(med_gain) - med_gain ) * 100)/lag(med_gain))%>%
#   na.omit()-> proc4summary_median

proc5summary_tbl%>%
  group_by(expr)%>%
  summarise(med_gain = median(time))%>%
  summarise(baUtilityR = ((lag(med_gain) - med_gain ) * 100)/lag(med_gain))%>%
  na.omit()-> proc5summary_median

proc6summary_tbl%>%
  group_by(expr)%>%
  summarise(med_gain = median(time))%>%
  summarise(flUtilityR = ((lag(med_gain) - med_gain ) * 100)/lag(med_gain))%>%
  na.omit()-> proc6summary_median

proc7summary_tbl%>%
  group_by(expr)%>%
  summarise(med_gain = median(time))%>%
  summarise(pCNLR = ((lag(med_gain) - med_gain ) * 100)/lag(med_gain))%>%
  na.omit()-> proc7summary_median

procsummary_median <- bind_cols(proc1summary_median,proc2summary_median,proc3summary_median,proc5summary_median,proc6summary_median,proc7summary_median)
prop_gain <- procsummary_median%>%
  pivot_longer(cols = c(psUtilityR,gaUtilityR,caUtilityR,baUtilityR,flUtilityR,pCNLR),names_to = "expr", values_to = "prop_gain")
prop_gain

vec_gains <-as.character(c(round(prop_gain[prop_gain$expr=='pCNLR',]$prop_gain),
             round(prop_gain[prop_gain$expr=='caUtilityR',]$prop_gain),
             round(prop_gain[prop_gain$expr=='gaUtilityR',]$prop_gain),
             round(prop_gain[prop_gain$expr=='psUtilityR',]$prop_gain),
             round(prop_gain[prop_gain$expr=='baUtilityR',]$prop_gain),
             round(prop_gain[prop_gain$expr=='flUtilityR',]$prop_gain)))
vec_gains <-paste0(vec_gains,'%')
fun_gains <- c('pCNLR','caUtilityR','gaUtilityR','psUtilityR', 'baUtilityR', 'flUtilityR')

p1_p<-ggplot(proc_time, aes(x = expr, y = ntime, fill=type))+
  geom_violin(trim = T)+
  xlab("")+
  ylab("time log10(ms)")+
  coord_flip() +
  theme_bw()+
  theme(legend.position = 'top',
        legend.title =element_blank() )+
  scale_fill_manual(values=c("#E69F00","#999999"))+
  geom_text(aes(x = fun_gains[1], y = 1), label=vec_gains[1],color="red")+
  geom_text(aes(x = fun_gains[2], y = 1.2), label=vec_gains[2],color="red")+
  geom_text(aes(x = fun_gains[3], y = 1), label=vec_gains[3],color="red")+
  geom_text(aes(x = fun_gains[4], y = 1), label=vec_gains[4],color="red")+
  geom_text(aes(x = fun_gains[5], y = 1), label=vec_gains[5],color="red") +
  geom_text(aes(x = fun_gains[6], y = 1), label=vec_gains[5],color="red")
p1_p
```

```{r, eval=FALSE}
ggsave(plot = p1_p, "performance_29_june_perc.png", dpi = 300, width = 7.5)
```


