# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Blocked-angle Utility
#'
#' @param aBA Power parameter.
#' @param bBA Scale parameter.
#' @param BA Numeric vector of distances from cells to closest pedestrians.
#' @param idx_BA Integer vector of cell indices.
#'
#' @return Numeric Vector of utilities for each cell.
#' @export
baUtility_rcpp <- function(aBA, bBA, BA, idx_BA) {
    .Call(`_m4ma_baUtility_rcpp`, aBA, bBA, BA, idx_BA)
}

#' Compute caUtility
#' @param aCA numeric vector
#' @param bCA numeric vector
#' @param bCAlr numeric vector
caUtility_rcpp <- function(aCA, bCA, bCAlr) {
    .Call(`_m4ma_caUtility_rcpp`, aCA, bCA, bCAlr)
}

#' Compute flUtility
#'
#' @param aFL numeric vector
#' @param bFL numeric vector
#' @param dFL numeric vector
#' @param leaders named numeric matrix 
#' @param dists transposed numeric matrix 
#' @return numeric vector of 33 elements
#' @export
flUtility_rcpp <- function(aFL, bFL, dFL, leaders, dists) {
    .Call(`_m4ma_flUtility_rcpp`, aFL, bFL, dFL, leaders, dists)
}

#' Compute gaUtility (Goal angle utility)
#'
#' @param bGA integer
#' @param aGA integer
#' @param GA numeric vector
#' @returns a numeric vector of length equal to GA's length 
#' @export
gaUtility_rcpp <- function(bGA, aGA, GA) {
    .Call(`_m4ma_gaUtility_rcpp`, bGA, aGA, GA)
}

#' Compute IDUtility
#'
#' @param bID numeric vector
#' @param dID numeric vector
#' @param aID numeric vector
#' @param n numeric vector
#' @param ok logical matrix 
#' @param group named numeric vector 
#' @param ID named numeric matrix 
#' @param ID_ is an empty matrix of the type NULL 
#' @returns a numeric vector of 33 elements 
#' @export
idUtility_rcpp <- function(bID, dID, aID, n, ok, group, ID_ = NULL) {
    .Call(`_m4ma_idUtility_rcpp`, bID, dID, aID, n, ok, group, ID_)
}

#' Probability of the Conditional Nested Logit Model
#'
#' @param cell Alternative vector with nest indices.
#' @param utility Vector with utility for each alternative.
#' @param mum Vector with nests associations ranging between 0 and 1.
#' @param nests List of vectors with utility indices.
#' @param alpha List of vectors with alpha values.
#' @param mu General nest association ranging between 0 and 1.
#'
#' @return Probability of alternative \code{cell} given \code{utility}, \code{alpha}, and parameters \code{mum} and \code{mu}.
#' @export
pcnl_rcpp <- function(cell, utility, mum, nests, alpha, mu) {
    .Call(`_m4ma_pcnl_rcpp`, cell, utility, mum, nests, alpha, mu)
}

#' Compute psUtility
#'
#' @param aPS numeric vector
#' @param sPref numeric vector
#' @param sSlow numeric vector
#' @param bPS numeric vector
#' @param v numeric vector
#' @param d numeric vector 
#' @returns a numeric vector of length equals to d's length 
#' @export
psUtility_rcpp <- function(aPS, sPref, sSlow, bPS, v, d) {
    .Call(`_m4ma_psUtility_rcpp`, aPS, sPref, sSlow, bPS, v, d)
}

